name: Deploy to Render
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Trigger Render Deployment
        run: |
          # Fetch the list of services and extract the service ID for the LegacyMarshal bot
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          https://api.render.com/v1/services?limit=20)
          
          SERVICE_ID=$(echo "$RESPONSE" | jq -r '.[] | select(.service.name == "LegacyMarshal") | .service.id')
          
          if [ -z "$SERVICE_ID" ]; then
            echo "Error: Could not find a service named 'LegacyMarshal'"
            exit 1
          fi
          
          # Trigger the deployment using the dynamically fetched service ID
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d "{\"serviceId\":\"$SERVICE_ID\"}" \
          https://api.render.com/v1/services/$SERVICE_ID/deploys